version: '3'
services: 
  db:
    image: postres
    restart: always
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    ports: 
      - 5432:5432

    enviroment:
      - POSTGRES_DB=sandeep
      - POSTGRES_USER=sandeepcode
      - POSTGRES_PASSWORD=sandeepsutharcode

  adminer:
     